Fix missing boost header
Fix compilation error:

In file included from /host/pqsmol-jan2016/DEVEL-SINGLE/dependencies/sjef/lib/sjef.cpp:1:
/host/pqsmol-jan2016/DEVEL-SINGLE/dependencies/sjef/lib/sjef.h:42:43: error: 'ipstream' is not a member of 'boost::process'
   42 |   mutable std::unique_ptr<boost::process::ipstream> m_status_stream;

ipstream etc. are all defined in pipe.hpp, see:
https://www.boost.org/doc/libs/1_73_0/doc/html/process/reference.html#header.boost.process.pipe_hpp